argocdNamespace: argocd

valuesFilename: aws-dcc-prod-values.yaml

# Default settings to remove some redundancy
default:
  app:
    source:
      extraSourceFields: |
#          helm:
#            valueFiles:
#            - {{ $.Values.valuesFilename }}
            
 
apps:
