argocdNamespace: argocd

valuesFilename: aws-dcc-prod-values.yaml

# Default settings to remove some redundancy
default:
  app:
    source:
      extraSourceFields: |
#          helm:
#            valueFiles:
#            - {{ $.Values.valuesFilename }}
            
apps:

  resc:
    source:
      repoURL: https://github.build.ge.com/digital-connect-devops/ec-service-argo-cd-apps.git
      path: resources
      targetRevision: HEAD
    destination:
      namespace: ec-service
      server: https://kubernetes.default.svc
    project: ec-service
    sync:
      enabled: true
      prune: true
      selfHeal: true

  svc-9e768876-7fe6-413c-8330-9e2d7ad42c7b:
    source:
      repoURL: https://github.build.ge.com/digital-connect-devops/ec-service-argo-cd-apps.git
      path: svc/9e768876-7fe6-413c-8330-9e2d7ad42c7b
      targetRevision: HEAD
    destination:
      namespace: ec-service
      server: https://kubernetes.default.svc
    project: ec-service
    sync:
      enabled: true
      prune: true
      selfHeal: true      

  svc-888d91ee-c556-4d31-869f-c6e937bfa7af:
    source:
      repoURL: https://github.build.ge.com/digital-connect-devops/ec-service-argo-cd-apps.git
      path: svc/888d91ee-c556-4d31-869f-c6e937bfa7af
      targetRevision: HEAD
    destination:
      namespace: ec-service
      server: https://kubernetes.default.svc
    project: ec-service
    sync:
      enabled: true
      prune: true
      selfHeal: true
