argocdNamespace: argocd

valuesFilename: aws-dcc-prod-values.yaml

# Default settings to remove some redundancy
default:
  app:
    source:
      extraSourceFields: |
#          helm:
#            valueFiles:
#            - {{ $.Values.valuesFilename }}
            
apps:

  resc:
    source:
      repoURL: https://github.build.ge.com/digital-connect-devops/ec-service-argo-cd-apps.git
      path: resources
      targetRevision: HEAD
    destination:
      namespace: ec-service
      server: https://kubernetes.default.svc
    project: ec-service
    sync:
      enabled: true
      prune: true
      selfHeal: true
