  svc-{{SVC_ID}}:
    source:
      repoURL: https://github.build.ge.com/digital-connect-devops/ec-service-argo-cd-apps.git
      path: svc/{{SVC_ID}}
      targetRevision: HEAD
    destination:
      namespace: ec-service
      server: https://kubernetes.default.svc
    project: ec-service
    sync:
      enabled: true
      prune: true
      selfHeal: true
