---
# begin ec autobot
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-{{SVC_ID}}
spec:
  selector:
    matchLabels:
      run: dpl-{{SVC_ID}}
  replicas: 1
  template:
    metadata:
      labels:
        run: dpl-{{SVC_ID}}
    spec:
      volumes:
        - name: svc-mount
          persistentVolumeClaim:
            claimName: ec-svc-efs-pvc
      containers:
      - name: sac-mstr-cntr
        volumeMounts:
          - name: svc-mount
            mountPath: "/root/.ec/sac-mstr/license"
            subPath: "prod/sac/master/sac-mstr/license"    
          - name: svc-mount
            mountPath: /root/.hash
            subPath: "./.hash"
        image: ghcr.io/ec-release/sac:master-eks
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 7991
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 101
        readinessProbe:
          tcpSocket:
            port: 7991
          initialDelaySeconds: 98
          failureThreshold: 10
          periodSeconds: 10
        env:
        - name: SAC_TYPE
          value: master
        - name: SAC_URL
          value: http://svc-{{SVC_ID}}.ec-service.svc.cluster.local:7991
        - name: EC_PORT
          value: :7991
        - name: EC_NOD
          value: {{EC_NOD}}:7991
        - name: EC_CID
          valueFrom:
            secretKeyRef:
              name: ec-secrets
              key: EC_CID
              optional: false
        ports:
          - containerPort: 7991
            name: sac-mst-port
            protocol: TCP

      - name: sac-slav-cntr
        volumeMounts:
          - name: svc-mount
            mountPath: "/root/.ec/.db"
            subPath: "prod/sac/slave/{{SVC_ID}}/.db"
          - name: svc-mount
            mountPath: /root/.hash
            subPath: "./.hash"
        image: ghcr.io/ec-release/sac:slave-eks
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:	
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 7992
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 200
        readinessProbe:
          tcpSocket:
            port: 7992
          initialDelaySeconds: 100
          failureThreshold: 10
          periodSeconds: 10
        env:
          - name: SAC_URL_MST
            value: http://localhost:7991
          - name: SAC_TYPE
            value: slave
          - name: SAC_URL
            value: http://svc-{{SVC_ID}}.ec-service.svc.cluster.local:7992
          - name: EC_NOD
            value: {{EC_NOD}}:7992
          - name: EC_PORT
            value: :7992
          - name: EC_CID
            valueFrom:
              secretKeyRef:
                name: ec-secrets
                key: EC_CID
                optional: false
        ports:
          - containerPort: 7992
            name: sac-slv-port
            protocol: TCP
      - name: svc
        image: ghcr.io/ec-release/svc:1.1-eks
        volumeMounts:
          - name: svc-mount
            mountPath: /root/svcs
            subPath: prod/svcs/{{SVC_ID}}
          - name: svc-mount
            mountPath: /root/.hash
            subPath: "./.hash"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:	
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /v1/info/
            port: http
          failureThreshold: 10
          periodSeconds: 90
          initialDelaySeconds: 100
        readinessProbe:
          httpGet:
            path: /v1/info/
            port: http
          initialDelaySeconds: 99
          failureThreshold: 10
          periodSeconds: 11
        env:
          - name: EC_SAC_MSTR_URL
            value: http://localhost:7991
          - name: EC_SAC_SLAV_URL
            value: http://localhost:7992
          - name: EC_SVC_URL
            value: http://svc-{{SVC_ID}}.ec-service.svc.cluster.local
          - name: ADMIN_USR
            value: admin
          - name: ADMIN_TKN
            value: {{SVC_ADM_TKN}}
          - name: EC_SETTING
            value: {{SVC_SETTING}}
          - name: EC_SVC_ID
            value: {{SVC_ID}}
          - name: EC_PORT
            value: :7990
          - name: EC_PRVT_PWD
            valueFrom:
              secretKeyRef:
                name: ec-secrets
                key: EC_PVT_PWD
                optional: false
          - name: EC_CID
            valueFrom:
              secretKeyRef:
                name: ec-secrets
                key: EC_CID
                optional: false
        ports:
          - containerPort: 7990
            name: http
            protocol: TCP
