---
# begin ec autobot
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: igs-{{SVC_ID}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{SVC_ID}}-ec-prod-aws.digitalconnect.apps.ge.com
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-{{SVC_ID}}
          servicePort: 80
# end of ec autobot          
